// generated by FLOKI_CONTROL_PLANE_RUNTIME_MIGRATION_REPAIR_V4
'use strict';

const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');

const {
  buildAuthorizationHeader
} = require('./sign-request.cjs');

function resolveSocketPath(config, projectRoot) {
  const configured = String(config.supervisor_local_socket_path || '');
  if (!configured) return null;
  return path.isAbsolute(configured)
    ? configured
    : path.resolve(projectRoot, configured);
}

function inspectLocalSocket(socketPath) {
  if (!socketPath) {
    return Object.freeze({
      available: false,
      reason: 'not_configured'
    });
  }
  let stat;
  try {
    stat = fs.lstatSync(socketPath);
  } catch (error) {
    if (error && error.code === 'ENOENT') {
      return Object.freeze({
        available: false,
        reason: 'missing'
      });
    }
    throw error;
  }
  if (!stat.isSocket()) {
    throw new Error(
      'configured supervisor local socket path is not a socket: ' +
      socketPath
    );
  }
  if ((stat.mode & 0o077) !== 0) {
    throw new Error(
      'configured supervisor local socket is not private (requires 0600): ' +
      socketPath
    );
  }
  return Object.freeze({
    available: true,
    reason: 'private_socket',
    socket_path: socketPath
  });
}

function resolvePrivateKey(config, env, projectRoot) {
  const configured = String(
    (env && env.FLOKI_CONTROL_PLANE_PRIVATE_KEY_PATH) ||
    config.supervisor_private_key_path ||
    ''
  );
  if (!configured) return null;
  const expanded = configured.replace(
    /^~(?=\/)/,
    (env && env.HOME) || process.env.HOME || ''
  );
  const resolved = path.isAbsolute(expanded)
    ? expanded
    : path.resolve(projectRoot, expanded);
  if (!fs.existsSync(resolved)) {
    throw new Error('supervisor private key not found: ' + resolved);
  }
  return fs.readFileSync(resolved, 'utf8').trim();
}

function buildSupervisorRequest(options = {}) {
  const config = options.config || {};
  const projectRoot = String(options.project_root || process.cwd());
  const moduleKey = String(options.module_key || '');
  const action = String(options.action || '');
  const body = options.body && typeof options.body === 'object'
    ? options.body
    : {};
  const env = options.env || process.env;
  if (!moduleKey || !action) {
    throw new Error('supervisor request requires module_key and action');
  }

  const payload = JSON.stringify(body);
  const route = '/modules/' + moduleKey + '/' + action;
  const socketPath = resolveSocketPath(config, projectRoot);
  const local = inspectLocalSocket(socketPath);
  if (local.available === true) {
    return Object.freeze({
      transport: 'local_unix_socket',
      payload,
      request_options: Object.freeze({
        socketPath,
        path: route,
        method: 'POST',
        headers: Object.freeze({
          'content-type': 'application/json',
          'content-length': Buffer.byteLength(payload)
        }),
        timeout: Number(
          config.supervisor_operation_timeout_ms || 360000
        )
      })
    });
  }

  const privateKey = resolvePrivateKey(config, env, projectRoot);
  if (!privateKey) {
    throw new Error(
      'supervisor local socket is unavailable (' + local.reason +
      ') and no signed TCP private key is configured'
    );
  }
  const signed = buildAuthorizationHeader(
    privateKey,
    'POST',
    moduleKey,
    action,
    payload
  );
  return Object.freeze({
    transport: 'signed_ed25519_tcp',
    payload,
    request_options: Object.freeze({
      host: config.supervisor_host,
      port: Number(config.supervisor_port),
      path: route,
      method: 'POST',
      headers: Object.freeze({
        'content-type': 'application/json',
        'content-length': Buffer.byteLength(payload),
        authorization: signed.header
      }),
      timeout: Number(
        config.supervisor_operation_timeout_ms || 360000
      )
    })
  });
}

function requestSupervisorLifecycle(options = {}) {
  return new Promise((resolve) => {
    let request;
    try {
      request = buildSupervisorRequest(options);
    } catch (error) {
      resolve(Object.freeze({
        ok: false,
        verified: false,
        error: error.message,
        httpStatus: 503,
        transport: null
      }));
      return;
    }

    let settled = false;
    const req = http.request(
      request.request_options,
      (response) => {
        let raw = '';
        response.setEncoding('utf8');
        response.on('data', (chunk) => { raw += chunk; });
        response.on('end', () => {
          if (settled) return;
          settled = true;
          try {
            const parsed = JSON.parse(raw);
            resolve(Object.freeze({
              ...(parsed && typeof parsed === 'object'
                ? parsed
                : {
                    ok: false,
                    verified: false,
                    error: 'invalid supervisor response'
                  }),
              httpStatus: Number(response.statusCode || 0),
              transport: request.transport
            }));
          } catch (_error) {
            resolve(Object.freeze({
              ok: false,
              verified: false,
              error: 'invalid supervisor response',
              httpStatus: 502,
              transport: request.transport
            }));
          }
        });
      }
    );
    req.on('error', (error) => {
      if (settled) return;
      settled = true;
      resolve(Object.freeze({
        ok: false,
        verified: false,
        error: error.message,
        httpStatus: 503,
        transport: request.transport
      }));
    });
    req.on('timeout', () => {
      if (settled) return;
      settled = true;
      req.destroy();
      resolve(Object.freeze({
        ok: false,
        verified: false,
        error: 'supervisor request timed out',
        httpStatus: 504,
        transport: request.transport
      }));
    });
    req.end(request.payload);
  });
}

module.exports = {
  resolveSocketPath,
  inspectLocalSocket,
  resolvePrivateKey,
  buildSupervisorRequest,
  requestSupervisorLifecycle
};
